// app/api/rag-chat/route.ts

// =============================================================================
// RAG API with Google Embeddings + Groq Answer Generation
// + Optional diagram spec generation + inline trigger token + SVG generation
// + Drawing analysis integration for UK/US
// + Document/Web source separation + inline citations + references block
// =============================================================================

import { createClient } from "@supabase/supabase-js";
import { GoogleGenAI } from "@google/genai";
import Groq from "groq-sdk";
import { NextResponse } from "next/server";
import { detectDiagramIntent } from "@/lib/diagram-intent-detector";
import { loadQuestionPatterns } from "@/lib/question-patterns-store";

export const runtime = "nodejs";

// =============================================================================
// ENV & SETUP
// =============================================================================

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY!;
const GROQ_API_KEY = process.env.GROQ_API_KEY!;
const TAVILY_API_KEY = process.env.TAVILY_API_KEY || "";

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
}

if (!GOOGLE_API_KEY) {
  throw new Error("Missing GOOGLE_API_KEY");
}

if (!GROQ_API_KEY) {
  throw new Error("Missing GROQ_API_KEY");
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
const ai = new GoogleGenAI({ apiKey: GOOGLE_API_KEY });
const groq = new Groq({ apiKey: GROQ_API_KEY });
const GROQ_CHAT_MODEL = "llama-3.3-70b-versatile";

// =============================================================================
// SYSTEM PROMPT (Multi-country + diagram rules)
// =============================================================================

const systemMessage = `You are an expert AI assistant specializing in construction regulations, urban planning, and real estate development across India, UK, and USA.

When users ask questions about buildable envelopes, setbacks, plot layouts, FSI/FAR/FSR, or zoning envelopes:

- Detect jurisdiction from context (India/UK/USA).
- Use correct units: India/UK -> metric (meters); USA -> imperial (feet).
- If exact local rules are not in provided sources, clearly label setbacks as "illustrative" and advise verification.
- Never invent clause/page numbers; only cite what is in sources.

Important:

- If a diagram is generated by the API, the response may include a JSON diagram spec followed by a token **[GENERATE_DIAGRAM]**.
- Do NOT fabricate JSON if you are not asked to; the API controls diagram JSON output.`;

// =============================================================================
// TYPES
// =============================================================================

interface EnhancedChunk {
  id: number;
  region: string;
  jurisdiction: string;
  doc_title: string;
  doc_path: string;
  doc_kind: string;
  doc_authority: string | null;
  doc_publication_date: string | null;
  doc_version: string | null;
  page_from: number | null;
  page_to: number | null;
  line_from: number | null;
  line_to: number | null;
  citation_type: string | null;
  citation_value: string | null;
  citation_full: string | null;
  clause_label: string | null;
  all_clauses: string | null;
  section_heading: string | null;
  section_hierarchy: string | null;
  cross_refs: any | null;
  table_refs: string[] | null;
  schedule_refs: string[] | null;
  annexure_refs: string[] | null;
  has_table: boolean;
  has_formula: boolean;
  has_diagram?: boolean;
  keywords: string[] | null;
  topic: string | null;
  subtopic: string | null;
  content: string;
  distance: number;
  indexed_at: string;
  updated_at: string | null;
}

interface TransformedCitation {
  id: string;
  title: string;
  type: string;
  sourceType?: "document" | "web";
  pageNumber?: number;
  clauseNumber?: string;
  section?: string;
  fullText: string;
  excerpt: string;
  confidence: number;
  lastUpdated: string;
  directLink?: string;
  sourceLabel?: string;
  _raw?: EnhancedChunk | any;
}

interface RagRequest {
  query: string;
  region?: "india" | "uk" | "usa" | null;
  topK?: number;
  threshold?: number;
  includeMetadata?: boolean;
  wantDiagram?: boolean;
  mode?: "auto" | "feasibility" | "permitting" | "risk";
  feasibilityInputs?: {
    city: string;
    jurisdictionCode?: string;
    zoneCode?: string;
    plotAreaSqm: number;
    builtUpSqm?: number;
    floors?: number;
    units?: number;
    useClass?: string;
  };
  drawingFile?: File | Blob | string;
}

type DiagramKind = "annotated_object" | "buildable_envelope";

interface DiagramPayload {
  kind: DiagramKind;
  title?: string;
  spec: any;
}

interface RagResponse {
  success: boolean;
  answer?: string;
  diagram?: DiagramPayload;
  svgContent?: string;
  data?: {
    citations: TransformedCitation[];
    query: string;
    region: string | null;
    resultsCount: number;
    metadata?: {
      avgDistance: number;
      documentsFound: number;
      citationTypes: Record<string, number>;
      authorities: Record<string, number>;
      topics: Record<string, number>;
    };
    references?: {
      documents: TransformedCitation[];
      web: TransformedCitation[];
    };
    missingCoverage?: Array<{
      questionPart: string;
      resolvedFrom: "document" | "web" | "unresolved";
    }>;
    feasibilityReport?: any;
    drawingValidation?: any;
  };
  metadata?: {
    processing_time?: number;
    confidence?: number;
    webFallbackUsed?: boolean;
  };
  error?: string;
}

// =============================================================================
// HELPERS
// =============================================================================

const GEMINI_EMBEDDING_MODEL =
  process.env.GEMINI_EMBEDDING_MODEL || "gemini-embedding-001";

async function generateEmbedding(text: string): Promise<number[]> {
  const cleanText = text.trim();
  if (!cleanText) {
    throw new Error("Cannot generate embedding for empty text");
  }

  const response = await ai.models.embedContent({
    model: GEMINI_EMBEDDING_MODEL,
    contents: cleanText,
  });

  const values = response.embeddings?.[0]?.values;
  if (!values?.length) {
    throw new Error("Embedding API returned no values");
  }

  return Array.from(values);
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function optimizeQuery(rawQuery: string): string {
  const fillers = [
    "according to",
    "how is it",
    "include the",
    "what is",
    "can you",
    "please",
    "tell me",
    "explain",
  ];
  let cleaned = rawQuery.toLowerCase();
  for (const f of fillers) {
    cleaned = cleaned.replace(new RegExp(escapeRegExp(f), "gi"), "");
  }
  const expansions: Record<string, string> = {
    fsi: "FSI Floor Space Index Floor Area Ratio FAR",
    fsr: "FSR Floor Space Ratio FAR FSI",
    far: "FAR Floor Area Ratio FSI FSR",
    dcr: "DCR Development Control Regulations",
    rera: "RERA Real Estate Regulation",
  };
  for (const key of Object.keys(expansions)) {
    if (cleaned.includes(key)) cleaned += " " + expansions[key];
  }
  return cleaned.trim();
}

function mapDocKindToCitationKind(docKind: string): string {
  const kindMap: Record<string, string> = {
    regulation: "government_doc",
    code: "government_doc",
    act: "legal_case",
    case: "legal_case",
    standard: "technical_standard",
    guideline: "technical_standard",
    rate: "rate_schedule",
  };
  return kindMap[String(docKind || "").toLowerCase()] || "government_doc";
}

function buildDocSourceLabel(chunk: EnhancedChunk, index: number): string {
  const page = chunk.page_from ? `p.${chunk.page_from}` : "p.n/a";
  const clause = chunk.clause_label ? `, Cl.${chunk.clause_label}` : "";
  return `D${index + 1} • ${page}${clause}`;
}

function stripChunkMetadata(text: string) {
  if (!text) return "";

  return text
    .replace(/\[TOPIC\]:?[^\n]*/gi, "")
    .replace(/\[SECTION\]:?[^\n]*/gi, "")
    .replace(/\[HEADING\]:?[^\n]*/gi, "")
    .replace(/\[KEYWORDS\]:?[^\n]*/gi, "")
    .replace(/\[NEXT_PAGE\]:?[^\n]*/gi, "")
    .replace(/\[PREV_PAGE\]:?[^\n]*/gi, "")
    .replace(/\s{2,}/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function repairSmashedWords(text: string) {
  if (!text) return "";

  return text
    .replace(/ONLIN[E]?VERSION/gi, "ONLINE VERSION")
    .replace(/ONLINE\s*VERSION/gi, "ONLINE VERSION")
    .replace(/ONLINEVERSION/gi, "ONLINE VERSION")
    .replace(/Buildungd|Buildungd|Buildundg|Buildingd/gi, "Building")
    .replace(/withbasement/gi, "with basement")
    .replace(/storeysthrough/gi, "storeys through")
    .replace(/Thefirefighting/gi, "The firefighting")
    .replace(/firefightingshaftsdo/gi, "firefighting shafts do")
    .replace(/storeyarea/gi, "storey area")
    .replace(/storeyheight/gi, "storey height")
    .replace(/vehiclebasements/gi, "vehicle access level basements")
    .replace(/accesslevel/gi, "access level")
    .replace(/Approved\s*Docu\s*ment/gi, "Approved Document")
    .replace(/Document\s*B\s*Volume/gi, "Document B Volume")
    .replace(/B\s*Volume/gi, "Volume")
    .replace(/Building\s*dR?I?B?u/gi, "")
    .replace(/\b([A-Za-z])\s(?=[A-Za-z]\s){2,}/g, (m) =>
      m.replace(/\s/g, "")
    )
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2")
    .replace(/(\d)([A-Za-z])/g, "$1 $2")
    .replace(/shaftscontaining/gi, "shafts containing")
    .replace(/shaftsshould/gi, "shafts should")
    .replace(/buildingwith/gi, "building with")
    .replace(/storeymore/gi, "storey more")
    .replace(/basementthat/gi, "basement that")
    .replace(/needone/gi, "need one")
    .replace(/storeythat/gi, "storey that")
    .replace(/building'sheight/gi, "building's height")
    .replace(/heightand size/gi, "height and size")
    .replace(/shaftsalso/gi, "shafts also")
    .replace(/storeys,each/gi, "storeys, each")
    .replace(/offirefighting/gi, "of firefighting")
    .replace(/shaftsare/gi, "shafts are")
    .replace(/shaftsin/gi, "shafts in")
    .replace(/ifbuildingsmeet/gi, "if buildings meet")
    .replace(/astorey/gi, "a storey")
    .replace(/Abuilding/gi, "A building")
    .replace(/abuilding/gi, "a building")
    .replace(/firefightingshaft/gi, "firefighting shaft")
    .replace(/firemain/gi, "fire main")
    .replace(/,The/g, ", the")
    .replace(/\.The/g, ". The")
    .replace(/\.There/g, ". There")
    .replace(/\.Fire/g, ". Fire")
    .replace(/\s{2,}/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function normalizeSentenceSpacing(text: string) {
  if (!text) return "";

  return text
    .replace(/([.?!;:])([A-Z])/g, "$1 $2")
    .replace(/([a-z])(\d+\.\d+)/g, "$1 $2")
    .replace(/(\d+\.\d+)([A-Z])/g, "$1 $2")
    .replace(/([a-z])([A-Z][a-z])/g, "$1 $2")
    .replace(/([a-z])([A-Z]{2,})/g, "$1 $2")
    .replace(/([a-z])\(/g, "$1 (")
    .replace(/\)\(/g, ") (")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function sanitizeEvidenceText(text: string) {
  return normalizeSentenceSpacing(
    repairSmashedWords(stripChunkMetadata(text || ""))
  );
}

function normalizedForMatching(text: string): string {
  return lower(sanitizeEvidenceText(text || ""))
    .replace(/\s+/g, " ")
    .trim();
}

function looksIncompleteEvidence(text: string) {
  if (!text) return false;

  const t = text.trim();
  if (!t) return false;

  const lastLine =
    t
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .pop() || t;

  return (
    /\b(and|or|to|of|for|with|including|which|that|where|when|if|than|see|paragraph|paragraphs)$/i.test(
      lastLine
    ) ||
    /\($/.test(lastLine) ||
    /[:;,-]$/.test(lastLine) ||
    /^(\d+\.|[a-z]\.)$/i.test(lastLine)
  );
}

function buildExcerpt(text: string, max = 240) {
  if (!text) return "";

  const cleaned = sanitizeEvidenceText(text);
  if (!cleaned) return "";

  const sentenceMatch = cleaned.match(/.*?[.!?](\s|$)/);
  const firstSentence = sentenceMatch?.[0]?.trim();

  if (
    firstSentence &&
    firstSentence.length >= 50 &&
    firstSentence.length <= max
  ) {
    return firstSentence;
  }

  return cleaned.length > max ? `${cleaned.slice(0, max).trim()}…` : cleaned;
}

function stitchAdjacentChunks(
  chunks: EnhancedChunk[],
  startIndex: number,
  maxChars = 2400
) {
  const base = chunks[startIndex];
  if (!base) return "";

  let assembled = sanitizeEvidenceText(base.content);
  if (!looksIncompleteEvidence(assembled)) return assembled;

  const sameDocFollowers = chunks
    .slice(startIndex + 1)
    .filter((c) => c.doc_title === base.doc_title)
    .sort((a, b) => {
      const aPage = a.page_from ?? 999999;
      const bPage = b.page_from ?? 999999;
      if (aPage !== bPage) return aPage - bPage;

      const aLine = a.line_from ?? 999999;
      const bLine = b.line_from ?? 999999;
      return aLine - bLine;
    });

  for (const next of sameDocFollowers) {
    const nextText = sanitizeEvidenceText(next.content);
    if (!nextText) continue;

    const nextPage = next.page_from ?? base.page_from ?? null;
    const basePage = base.page_from ?? null;
    if (basePage != null && nextPage != null && nextPage - basePage > 2) {
      break;
    }

    assembled = `${assembled} ${nextText}`.replace(/\s{2,}/g, " ").trim();

    if (!looksIncompleteEvidence(assembled) || assembled.length >= maxChars) {
      break;
    }
  }

  return assembled.slice(0, maxChars).trim();
}

function transformChunksForFrontend(
  chunks: EnhancedChunk[]
): TransformedCitation[] {
  return chunks.map((chunk, index) => {
    const stitchedFullText = stitchAdjacentChunks(chunks, index);
    const cleanedFullText = sanitizeEvidenceText(
      stitchedFullText || chunk.content
    );

    return {
      id: `D${index + 1}`,
      title: chunk.doc_title,
      type: mapDocKindToCitationKind(chunk.doc_kind),
      sourceType: "document",
      pageNumber: chunk.page_from ?? undefined,
      clauseNumber:
        chunk.citation_value && String(chunk.citation_value).trim()
          ? String(chunk.citation_value).trim()
          : undefined,
      section: chunk.section_heading ?? chunk.section_hierarchy ?? undefined,
      fullText: cleanedFullText,
      excerpt: buildExcerpt(cleanedFullText, 220),
      confidence: Math.round(
        Math.max(0, Math.min(100, (1 - chunk.distance) * 100))
      ),
      lastUpdated: chunk.indexed_at,
      directLink: chunk.doc_path?.startsWith("http")
        ? chunk.doc_path
        : undefined,
      sourceLabel: buildDocSourceLabel(chunk, index),
      _raw: {
        ...chunk,
        originalContent: chunk.content,
        backendSanitized: true,
        stillLooksIncomplete: looksIncompleteEvidence(cleanedFullText),
      },
    };
  });
}

function dedupeCitations(
  citations: TransformedCitation[]
): TransformedCitation[] {
  const seen = new Set<string>();

  return citations.filter((c) => {
    const normalizedExcerpt = (c.excerpt || "")
      .toLowerCase()
      .replace(/\s+/g, " ")
      .replace(/diagram\s+\d+(\.\d+)?/g, "")
      .trim()
      .slice(0, 90);

    const key = [
      c.title || "",
      c.pageNumber || "",
      c.clauseNumber || "",
      normalizedExcerpt,
    ].join("|");

    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function calculateConfidence(avgDistance: number, chunkCount: number): number {
  let conf = Math.max(0, 1 - avgDistance);
  if (avgDistance < 0.3) conf = Math.min(1, conf * 1.15);
  if (chunkCount < 3) conf *= 0.7;
  if (chunkCount >= 5) conf *= 1.05;
  return Math.min(1, conf);
}

function calculateMetadata(chunks: EnhancedChunk[]) {
  const docs = new Set<string>();
  const citationTypes: Record<string, number> = {};
  const authorities: Record<string, number> = {};
  const topics: Record<string, number> = {};
  let totalDistance = 0;

  for (const c of chunks) {
    totalDistance += c.distance;
    docs.add(c.doc_title);
    if (c.citation_type) {
      citationTypes[c.citation_type] =
        (citationTypes[c.citation_type] || 0) + 1;
    }
    if (c.doc_authority) {
      authorities[c.doc_authority] = (authorities[c.doc_authority] || 0) + 1;
    }
    if (c.topic) topics[c.topic] = (topics[c.topic] || 0) + 1;
  }

  return {
    avgDistance: chunks.length ? totalDistance / chunks.length : 0,
    documentsFound: docs.size,
    citationTypes,
    authorities,
    topics,
  };
}

function lower(value: unknown): string {
  return String(value || "").toLowerCase();
}

function hasAny(text: string, terms: string[]): boolean {
  return terms.some((t) => text.includes(t));
}

function uniqueTerms(query: string): string[] {
  return Array.from(
    new Set(
      query
        .toLowerCase()
        .replace(/[^a-z0-9.\s-]/g, " ")
        .split(/\s+/)
        .map((x) => x.trim())
        .filter((x) => x.length >= 2)
    )
  );
}

function countMatches(text: string, terms: string[]): number {
  return terms.reduce((acc, t) => acc + (text.includes(t) ? 1 : 0), 0);
}

function isRequirementDefinitionQuery(query: string): boolean {
  const q = lower(query);
  return (
    q.includes("requirement b1") ||
    q.includes("requirement b2") ||
    q.includes("requirement b3") ||
    q.includes("requirement b4") ||
    q.includes("requirement b5") ||
    q.includes("what is requirement") ||
    q.includes("what does requirement")
  );
}

function isTableQuery(query: string): boolean {
  const q = lower(query);
  return (
    q.includes("table ") ||
    q.includes("travel distance") ||
    q.includes("single direction") ||
    q.includes("alternative escape") ||
    q.includes("maximum travel distance") ||
    q.includes("values") ||
    q.includes("limits")
  );
}

function isThresholdQuery(query: string): boolean {
  const q = lower(query);
  return (
    q.includes("when is") ||
    q.includes("required") ||
    q.includes("threshold") ||
    q.includes("minimum") ||
    q.includes("maximum") ||
    q.includes("11m") ||
    q.includes("18m") ||
    q.includes("firefighting shaft") ||
    q.includes("regulation 38")
  );
}

function extractRequestedTable(query: string): string | null {
  const m = lower(query).match(/\btable\s+([a-z]?\d+(?:\.\d+)?)\b/);
  return m?.[1] || null;
}

function getFirefightingShaftClausePriority(chunk: EnhancedChunk): number {
  const text = normalizedForMatching(chunk.content || "");
  const clause = lower(chunk.clause_label);
  const citation = lower(chunk.citation_value);
  const heading = normalizedForMatching(chunk.section_heading || "");
  const section = normalizedForMatching(chunk.section_hierarchy || "");

  let score = 0;

  const isMain17_2 =
    clause === "17.2" ||
    citation === "17.2" ||
    text.includes("17.2") ||
    text.includes(
      "storey more than 18 m above the fire and rescue service vehicle access level"
    );

  const isBasement17_3 =
    clause === "17.3" ||
    citation === "17.3" ||
    text.includes("17.3") ||
    text.includes("basement more than 10 m below") ||
    text.includes("two or more basement storeys");

  const isService17_4 =
    clause === "17.4" ||
    citation === "17.4" ||
    text.includes("17.4") ||
    text.includes("should serve all storeys through which they pass");

  const isMulti17_5 =
    clause === "17.5" ||
    citation === "17.5" ||
    text.includes("17.5") ||
    text.includes("minimum of two firefighting shafts");

  const isSpecial17_6 =
    clause === "17.6" ||
    citation === "17.6" ||
    text.includes("17.6") ||
    text.includes("at least two firefighting shafts");

  const isDiagramOnly =
    !text.includes("should have") &&
    !text.includes("required") &&
    !text.includes("must be provided") &&
    (heading.includes("diagram") ||
      section.includes("diagram") ||
      text.startsWith("diagram 17.1") ||
      text.startsWith("diagram 17.2") ||
      text.includes("components of a firefighting shaft") ||
      text.includes("location of firefighting shafts"));

  if (isMain17_2) score += 100;
  if (isBasement17_3) score += 60;
  if (isService17_4) score += 35;
  if (isMulti17_5) score += 30;
  if (isSpecial17_6) score += 25;
  if (text.includes("18 m")) score += 10;
  if (text.includes("firefighting shaft")) score += 8;
  if (isDiagramOnly) score -= 80;

  return score;
}

function countDirtyChunks(chunks: EnhancedChunk[]): number {
  return chunks.filter((c) => {
    const raw = c.content || "";
    return (
      /ONLINE\s*VERSION/i.test(raw) ||
      /firefightingshafts/i.test(raw) ||
      /shaftsandprotected/i.test(raw) ||
      /Approved\s*Docu\s*ment/i.test(raw) ||
      /\b[A-Za-z]{10,}[A-Z][a-z]+\b/.test(raw)
    );
  }).length;
}

function reRankByKeywords(
  chunks: EnhancedChunk[],
  query: string
): EnhancedChunk[] {
  const queryTerms = query.toLowerCase().split(/\s+/).filter(Boolean);
  const scored = chunks.map((chunk: any) => {
    const content = chunk.content.toLowerCase();
    let keywordScore = 0;

    for (const term of queryTerms) {
      if (term.length <= 3) continue;
      try {
        const matches =
          (content.match(new RegExp(escapeRegExp(term), "g")) || []).length;
        keywordScore += matches;
      } catch {}
    }

    if (
      chunk.clause_label &&
      query.toLowerCase().includes(chunk.clause_label.toLowerCase())
    ) {
      keywordScore += 10;
    }
    if (chunk.citation_value && query.includes(chunk.citation_value)) {
      keywordScore += 15;
    }

    return { ...chunk, keywordScore };
  });

  return scored.sort((a: any, b: any) => {
    const distanceDiff = a.distance - b.distance;
    if (Math.abs(distanceDiff) > 0.05) return distanceDiff;
    return (b.keywordScore || 0) - (a.keywordScore || 0);
  });
}

function reRankByCitations(
  chunks: EnhancedChunk[],
  query: string
): EnhancedChunk[] {
  const citationKeywords = [
    "section",
    "regulation",
    "clause",
    "rule",
    "table",
    "schedule",
    "paragraph",
    "article",
  ];
  const hasCitationQuery = citationKeywords.some((kw) =>
    query.toLowerCase().includes(kw)
  );
  if (!hasCitationQuery) return chunks;

  const m = query.match(/\b(\d+(?:\.\d+)*)\b/);
  const queryCitation = m ? m[1] : null;

  return [...chunks].sort((a, b) => {
    const aHas = a.citation_value ? 1 : 0;
    const bHas = b.citation_value ? 1 : 0;
    if (aHas !== bHas) return bHas - aHas;

    if (queryCitation) {
      const am = a.citation_value?.includes(queryCitation) ? 1 : 0;
      const bm = b.citation_value?.includes(queryCitation) ? 1 : 0;
      if (am !== bm) return bm - am;
    }

    return a.distance - b.distance;
  });
}

function rankRetrievedChunks(
  query: string,
  chunks: EnhancedChunk[]
): EnhancedChunk[] {
  const q = lower(query);
  const queryTerms = uniqueTerms(query);
  const requestedTable = extractRequestedTable(query);

  const ranked = chunks.map((chunk) => {
    const heading = lower(chunk.section_heading);
    const section = lower(chunk.section_hierarchy);
    const content = lower(chunk.content);
    const topic = lower(chunk.topic);
    const clause = lower(chunk.clause_label);
    const citationType = lower(chunk.citation_type);
    const citationValue = lower(chunk.citation_value);
    const tableRefs = (chunk.table_refs || []).map((t) => lower(t));
    const keywords = (chunk.keywords || []).map((k) => lower(k));

    let boost = 0;
    let penalty = 0;

    const combined = [
      heading,
      section,
      topic,
      clause,
      keywords.join(" "),
      content.slice(0, 1400),
    ].join(" ");

    const lexicalHits = countMatches(combined, queryTerms);
    boost += Math.min(0.22, lexicalHits * 0.02);

    if (
      content.includes("top storey") ||
      content.includes("storey height") ||
      content.includes("building height")
    ) {
      boost += 0.3;
    }

    if (heading && q.includes(heading)) boost += 0.22;
    if (section && q.includes(section)) boost += 0.16;
    if (clause && q.includes(clause)) boost += 0.12;

    if (isRequirementDefinitionQuery(query)) {
      if (heading.includes("requirement")) boost += 0.25;
      if (section.includes("requirement")) boost += 0.2;
      if (
        content.includes("the building shall be designed and constructed") ||
        content.includes("means of warning and escape") ||
        content.includes("internal fire spread") ||
        content.includes("external fire spread") ||
        content.includes("access and facilities for the fire service")
      ) {
        boost += 0.25;
      }

      if (
        !heading.includes("requirement") &&
        !section.includes("requirement") &&
        !content.includes("the building shall be designed and constructed")
      ) {
        penalty += 0.12;
      }
    }

    if (isTableQuery(query)) {
      if (citationType === "table") boost += 0.35;
      if (content.includes("table")) boost += 0.12;

      if (requestedTable) {
        if (citationValue === requestedTable) boost += 0.5;
        if (tableRefs.includes(requestedTable)) boost += 0.5;
        if (content.includes(`table ${requestedTable}`)) boost += 0.45;
      }

      if (
        hasAny(content, [
          "travel distance",
          "single direction",
          "alternative escape",
          "more than one available escape route",
          "one available escape route",
        ])
      ) {
        boost += 0.25;
      }

      if (/\b\d+\s?m\b/.test(content)) boost += 0.15;

      if (
        content.includes("single direction") &&
        content.includes("alternative escape")
      ) {
        boost += 0.25;
      }

      if (
        citationType !== "table" &&
        !tableRefs.length &&
        !content.includes("table")
      ) {
        penalty += 0.25;
      }
    }

    if (isThresholdQuery(query)) {
      if (
        !content.includes("18m") &&
        !content.includes("18 m") &&
        !content.includes("top storey") &&
        !content.includes("height") &&
        !content.includes("storey")
      ) {
        penalty += 0.4;
      }

      if (content.includes("11m")) boost += 0.12;
      if (content.includes("18m") || content.includes("18 m")) boost += 0.2;

      if (content.includes("firefighting shaft")) boost += 0.35;
      if (content.includes("firefighting lift")) boost += 0.25;

      if (
        content.includes("access for fire service") ||
        content.includes("fire service access") ||
        content.includes("facilities for the fire service")
      ) {
        boost += 0.25;
      }

      if (
        content.includes("section 15") ||
        content.includes("section 16") ||
        content.includes("firefighting access") ||
        content.includes("firefighting shafts")
      ) {
        boost += 0.4;
      }

      if (content.includes("required")) boost += 0.1;
      if (content.includes("regulation 38")) boost += 0.2;
    }

    if (
      heading === "contents" ||
      heading.includes("appendix") ||
      content.includes("see section") ||
      content.includes("see paragraph") ||
      content.includes("for guidance see")
    ) {
      penalty += 0.1;
    }

    const finalScore = 1 - chunk.distance + boost - penalty;

    return {
      ...chunk,
      _rankBoost: boost,
      _rankPenalty: penalty,
      _finalScore: Number(finalScore.toFixed(4)),
    } as EnhancedChunk & {
      _rankBoost: number;
      _rankPenalty: number;
      _finalScore: number;
    };
  });

  return ranked.sort(
    (a: any, b: any) => (b._finalScore || 0) - (a._finalScore || 0)
  );
}

function shouldUseWebFallback(query: string, chunks: EnhancedChunk[]): boolean {
  if (!chunks.length) return true;

  const q = lower(query);

  if (
    q.includes("approved document b") ||
    q.includes("national building code of india") ||
    q.includes("nbc india") ||
    q.includes("mohua") ||
    q.includes("rera") ||
    q.includes("affordable housing development guidelines")
  ) {
    return false;
  }

  if (
    q.includes("requirement b1") ||
    q.includes("requirement b2") ||
    q.includes("requirement b3") ||
    q.includes("requirement b4") ||
    q.includes("requirement b5") ||
    q.includes("regulation 38") ||
    q.includes("table 2.1")
  ) {
    return false;
  }

  if (chunks.length < 2) return true;
  const avgDistance =
    chunks.reduce((sum, c) => sum + c.distance, 0) / chunks.length;
  return avgDistance > 0.55;
}

async function fetchWebFallback(query: string): Promise<TransformedCitation[]> {
  if (!TAVILY_API_KEY) return [];

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);

  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        api_key: TAVILY_API_KEY,
        query,
        max_results: 3,
        search_depth: "advanced",
        include_answer: false,
        include_raw_content: false,
      }),
      signal: controller.signal,
    });

    if (!res.ok) return [];

    const json = await res.json();
    const results = Array.isArray(json?.results) ? json.results : [];

    return results.map((r: any, index: number) => ({
      id: `W${index + 1}`,
      title: r.title || `Web Source ${index + 1}`,
      type: "web",
      sourceType: "web",
      pageNumber: undefined,
      clauseNumber: undefined,
      section: undefined,
      fullText: sanitizeEvidenceText(r.content || r.snippet || ""),
      excerpt: buildExcerpt(r.content || r.snippet || "", 220),
      confidence: 62,
      lastUpdated: new Date().toISOString(),
      directLink: r.url,
      sourceLabel: `W${index + 1} • taken from web`,
      _raw: r,
    }));
  } catch (error) {
    console.error("Web fallback failed:", error);
    return [];
  } finally {
    clearTimeout(timeout);
  }
}

function buildDocumentContext(chunks: EnhancedChunk[]): string {
  if (chunks.length === 0) return "";

  return chunks
    .slice(0, 5)
    .map((c, idx) => {
      const n = `D${idx + 1}`;
      const page = c.page_from ? `Page ${c.page_from}` : "Page n/a";
      const clause = c.clause_label ? `Clause ${c.clause_label}` : "Clause n/a";
      const section = c.section_heading || c.section_hierarchy || "Section n/a";
      const cleaned = sanitizeEvidenceText(c.content || "");
      const text =
        cleaned.length > 1500 ? cleaned.slice(0, 1500) + "..." : cleaned;
      return `[${n}] ${c.doc_title} — ${page} — ${clause} — ${section}\n${text}`;
    })
    .join("\n\n");
}

function chooseChunksForAnswer(
  query: string,
  chunks: EnhancedChunk[]
): EnhancedChunk[] {
  const top = chunks.slice(0, 8);

  if (isRequirementDefinitionQuery(query)) {
    const defs = top.filter((c) => {
      const heading = lower(c.section_heading);
      const section = lower(c.section_hierarchy);
      const content = lower(c.content);
      return (
        heading.includes("requirement") ||
        section.includes("requirement") ||
        content.includes("the building shall be designed and constructed")
      );
    });

    if (defs.length) return defs.slice(0, 4);
  }

  if (isTableQuery(query)) {
    return chunks
      .filter((c) => {
        const content = lower(c.content);
        return (
          content.includes("table 2.1") ||
          content.includes("travel distance") ||
          /\b\d+\s?m\b/.test(content)
        );
      })
      .slice(0, 6);
  }

  if (isThresholdQuery(query)) {
    const thresholdChunks = top
      .map((c) => ({
        chunk: c,
        priority: getFirefightingShaftClausePriority(c),
      }))
      .filter(({ priority, chunk }) => {
        const text = lower(chunk.content);
        return (
          priority > 0 ||
          text.includes("required") ||
          text.includes("must be provided") ||
          text.includes("regulation 38")
        );
      })
      .sort(
        (a, b) => b.priority - a.priority || a.chunk.distance - b.chunk.distance
      )
      .map(({ chunk }) => chunk);

    if (thresholdChunks.length) {
      return thresholdChunks.slice(0, 6);
    }
  }

  return chunks.slice(0, 10);
}

function buildStrictDocumentContext(chunks: EnhancedChunk[]): string {
  if (chunks.length === 0) return "";

  return chunks
    .map((c, idx) => {
      const n = `D${idx + 1}`;
      const page = c.page_from ? `Page ${c.page_from}` : "Page n/a";
      const clause = c.clause_label ? `Clause ${c.clause_label}` : "Clause n/a";
      const section = c.section_heading || c.section_hierarchy || "Section n/a";
      const citationType = c.citation_type || "unknown";
      const citationValue = c.citation_value || "unknown";
      const tableRefs = (c.table_refs || []).join(", ") || "none";
      const cleaned = sanitizeEvidenceText(c.content || "");
      const text =
        cleaned.length > 1400 ? cleaned.slice(0, 1400) + "..." : cleaned;
      return [
        `CHUNK_ID: ${n}`,
        `DOC: ${c.doc_title}`,
        `PAGE: ${page}`,
        `HEADING: ${section}`,
        `CLAUSE: ${clause}`,
        `CITATION_TYPE: ${citationType}`,
        `CITATION_VALUE: ${citationValue}`,
        `TABLE_REFS: ${tableRefs}`,
        `CONTENT:\n${text}`,
      ].join("\n");
    })
    .join("\n\n--------------------\n\n");
}

function buildWebContext(webSources: TransformedCitation[]): string {
  if (webSources.length === 0) return "";

  return webSources
    .map((w) => {
      const text =
        w.fullText.length > 500 ? w.fullText.slice(0, 500) + "..." : w.fullText;
      return `[${w.id}] ${w.title}\n${text}`;
    })
    .join("\n\n");
}

function buildReferencesBlock(
  documentCitations: TransformedCitation[],
  webCitations: TransformedCitation[]
): string {
  const docRefs = documentCitations.map(
    (c) => `- ${formatVerifiedReference(c)}`
  );

  const webRefs = webCitations.map((c) => {
    const bits = [
      `[${c.id}]`,
      c.title,
      "taken from web",
      `Confidence ${c.confidence}%`,
    ];
    return `- ${bits.join(" — ")}`;
  });

  let out = `\n\n### References`;

  if (docRefs.length > 0) {
    out += `\n\n**Document References**\n${docRefs.join("\n")}`;
  }

  if (webRefs.length > 0) {
    out += `\n\n**Web References**\n${webRefs.join("\n")}`;
  }

  return out;
}

function forceAtLeastOneInlineCitation(
  answer: string,
  documentCitations: TransformedCitation[],
  webCitations: TransformedCitation[]
): string {
  let updated = answer;

  const isFallback =
    updated.includes("I cannot answer reliably from the indexed documents.") ||
    updated.includes("This appears to be outside the indexed dataset.");

  if (isFallback) return updated;

  if (documentCitations.length > 0 && !/\[D\d+\]/.test(updated)) {
    updated += `\n\nPrimary document support: [${documentCitations[0].id}]`;
  }

  if (webCitations.length > 0 && !/\[W\d+\]/.test(updated)) {
    updated += `\n\nMissing parts supplemented from web: [${webCitations[0].id}]`;
  }

  return updated;
}

function buildExtractionPrompt(query: string, chunksFormatted: string): string {
  return `
You are a regulatory extraction engine.

STRICT RULES:
1. If the answer exists in the provided chunks, you MUST extract it.
2. Do NOT say "not explicitly stated", "not specified", or "not defined" unless the information is truly absent from all provided chunks.
3. Prefer exact regulatory wording first, then explain it clearly.
4. If the user asks about a Requirement, prioritise the chunk that defines it.
5. If the user asks about a table, prioritise the chunk containing the table or its values.
6. If thresholds or conditions are implied across multiple chunks, combine them logically.
7. Do not invent facts.
8. Use only the provided chunks.
9. The answer must be detailed and structured, not minimal.
10. Return valid JSON only.

User query:
${query}

Provided chunks:
${chunksFormatted}

Return JSON in this exact shape:
{
  "answerMarkdown": "detailed markdown answer with inline citations like [D1], [D2]",
  "missingCoverage": [
    {
      "questionPart": "string",
      "resolvedFrom": "document" | "web" | "unresolved"
    }
  ]
}
`.trim();
}

function extractFirstJsonObject(text: string): string | null {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  return text.slice(start, end + 1);
}

function detectRequestedJurisdiction(
  query: string
): "uk" | "india" | "usa" | null {
  const q = lower(query);

  if (
    q.includes("nfpa") ||
    q.includes("ibc") ||
    q.includes("irc") ||
    q.includes("usa") ||
    q.includes("us ")
  ) {
    return "usa";
  }

  if (
    q.includes("approved document") ||
    q.includes("uk") ||
    q.includes("british standard") ||
    q.includes("bs ")
  ) {
    return "uk";
  }

  if (
    q.includes("nbc india") ||
    q.includes("national building code of india") ||
    q.includes("mohua") ||
    q.includes("rera") ||
    q.includes("india")
  ) {
    return "india";
  }

  return null;
}

function detectRequestedDocumentRegion(
  query: string
): "uk" | "india" | "usa" | null {
  const q = lower(query);

  if (
    q.includes("affordable housing development guidelines") ||
    q.includes("affordable housing how-to guide") ||
    q.includes("land use application nyc") ||
    q.includes("land use map guidelines")
  ) {
    return "usa";
  }

  if (
    q.includes("approved document b") ||
    q.includes("town and country planning act") ||
    q.includes("nppf") ||
    q.includes("neighbourhood planning")
  ) {
    return "uk";
  }

  if (
    q.includes("national building code of india") ||
    q.includes("mohua") ||
    q.includes("rera") ||
    q.includes("navi mumbai")
  ) {
    return "india";
  }

  return null;
}

function isComparisonQuery(query: string): boolean {
  const q = lower(query);
  return (
    q.includes("compare") ||
    q.includes("difference between") ||
    q.includes("vs") ||
    q.includes("versus")
  );
}

function dominantJurisdiction(
  chunks: EnhancedChunk[]
): "uk" | "india" | "usa" | null {
  if (!chunks.length) return null;

  const counts: Record<string, number> = {};
  for (const c of chunks) {
    const key = lower(c.region || c.jurisdiction);
    if (!key) continue;
    counts[key] = (counts[key] || 0) + 1;
  }

  const top =
    Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] || null;
  if (top === "uk" || top === "india" || top === "usa") return top;
  return null;
}

function hasJurisdictionMismatch(
  query: string,
  chunks: EnhancedChunk[]
): boolean {
  if (isComparisonQuery(query)) return false;

  const requested = detectRequestedJurisdiction(query);
  const dominant = dominantJurisdiction(chunks);

  if (!requested || !dominant) return false;
  return requested !== dominant;
}

function getTopSimilarityScore(chunks: EnhancedChunk[]): number {
  if (!chunks.length) return 0;
  return 1 - (chunks[0].distance ?? 1);
}

function isOutsideDatasetQuery(query: string): boolean {
  const q = lower(query);

  if (q.includes("nfpa 13")) return true;

  return false;
}

function buildOutsideDatasetAnswer(): string {
  return `
### Direct Answer
This appears to be outside the indexed dataset.

### Notes
I cannot answer reliably from the currently indexed documents for this query.
  `.trim();
}

function buildPartialCoverageAnswer(): string {
  return `
### Direct Answer
I cannot answer reliably from the indexed documents.

### Notes
Relevant material may be partially related, but the retrieved context is not strong enough to support a grounded answer.
  `.trim();
}

function formatVerifiedReference(c: TransformedCitation): string {
  const bits = [`[${c.id}]`, c.title];

  if (c.pageNumber) bits.push(`Page ${c.pageNumber}`);
  if (c.clauseNumber) bits.push(`Clause ${c.clauseNumber}`);
  bits.push(`Confidence ${c.confidence}%`);

  return bits.join(" — ");
}

function shouldRejectWeakExtraction(query: string, answer: string): boolean {
  const q = lower(query);
  const a = lower(answer);

  const weakPatterns = [
    "not explicitly stated",
    "not specified",
    "not defined",
    "not provided",
    "mentioned but",
    "unresolved",
  ];

  if (weakPatterns.some((p) => a.includes(p))) {
    if (
      q.includes("requirement b1") ||
      q.includes("requirement b2") ||
      q.includes("requirement b3") ||
      q.includes("requirement b4") ||
      q.includes("requirement b5") ||
      q.includes("table 2.1") ||
      q.includes("travel distance") ||
      q.includes("firefighting shaft") ||
      q.includes("regulation 38")
    ) {
      return true;
    }
  }

  return false;
}

// =============================================================================
// ✅ NEW: DIAGRAM JSON EXTRACTION & CLEANUP FUNCTIONS
// =============================================================================

function shouldGenerateDiagram(response: string): boolean {
  return (
    response.includes('"kind": "buildable_envelope"') ||
    response.includes('"kind": "annotated_object"') ||
    response.includes("buildable envelope")
  );
}

function extractDiagramSpec(response: string): DiagramPayload | null {
  const jsonMatch = response.match(/```json\s*([\s\S]*?)```/i);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);
      if (parsed.diagram) {
        return {
          kind: parsed.diagram.kind,
          spec: parsed.diagram.spec,
        };
      }
      return parsed;
    } catch (e) {
      console.error("Failed to parse diagram JSON:", e);
      return null;
    }
  }
  return null;
}

function removeJsonBlock(text: string): string {
  return text
    .replace(/```json\s*[\s\S]*?```/gi, "")
    .replace(/\*\*\[GENERATE_DIAGRAM\]\*\*/g, "")
    .replace(/Here is the diagram spec with jurisdiction metadata:/gi, "")
    .trim();
}

// =============================================================================
// ✅ NEW: SVG DIAGRAM GENERATOR
// =============================================================================

function generateDiagramSVG(diagramPayload: DiagramPayload): string {
  const { spec } = diagramPayload;
  const { site, setbacks } = spec;

  const plotLength = site.dimensions?.length || 40;
  const plotWidth = site.dimensions?.width || 30;

  const buildableLength = plotLength - setbacks.front - setbacks.rear;
  const buildableWidth = plotWidth - setbacks.left - setbacks.right;
  const buildableArea = buildableLength * buildableWidth;
  const totalArea = plotLength * plotWidth;
  const coverage = ((buildableArea / totalArea) * 100).toFixed(2);

  const scale = 10;
  const padding = 60;
  const headerHeight = 100;
  const footerHeight = 60;
  const legendWidth = 240;

  const diagramWidth = plotLength * scale;
  const diagramHeight = plotWidth * scale;
  const totalWidth = diagramWidth + padding * 2 + legendWidth;
  const totalHeight = diagramHeight + padding * 2 + headerHeight + footerHeight;

  const jurisdiction = spec.meta?.jurisdiction?.toUpperCase() || "INDIA";
  const regulation = setbacks.regulation || "Local regulations";

  return `
<svg xmlns="http://www.w3.org/2000/svg" width="${totalWidth}" height="${totalHeight}" viewBox="0 0 ${totalWidth} ${totalHeight}">
  <rect width="${totalWidth}" height="${totalHeight}" fill="#0a0a0a"/>
  <text x="${padding}" y="40" font-family="system-ui" font-size="18" font-weight="600" fill="#e5e7eb">
    Buildable Envelope for ${plotLength}m × ${plotWidth}m Plot (${jurisdiction})
  </text>
  <text x="${padding}" y="65" font-family="system-ui" font-size="12" fill="#9ca3af">
    ${plotLength}m × ${plotWidth}m • ${regulation}
  </text>
  <text x="${padding}" y="85" font-family="system-ui" font-size="11" fill="#6b7280">
    Buildable area: ${buildableArea.toFixed(2)} sqm • Coverage: ${coverage}%
  </text>
  <rect x="${padding}" y="${headerHeight}" width="${diagramWidth}" height="${diagramHeight}" 
        fill="none" stroke="#3b82f6" stroke-width="2" stroke-dasharray="5,5"/>
  <rect x="${padding + setbacks.left * scale}" y="${headerHeight + setbacks.front * scale}" 
        width="${buildableLength * scale}" height="${buildableWidth * scale}" 
        fill="#22c55e22" stroke="#22c55e" stroke-width="2"/>
  <text x="${padding}" y="${headerHeight + diagramHeight + 30}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Front: ${setbacks.front}m
  </text>
  <text x="${padding}" y="${headerHeight + diagramHeight + 45}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Rear: ${setbacks.rear}m
  </text>
  <text x="${padding + 120}" y="${headerHeight + diagramHeight + 30}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Left: ${setbacks.left}m
  </text>
  <text x="${padding + 120}" y="${headerHeight + diagramHeight + 45}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Right: ${setbacks.right}m
  </text>
  <text x="${diagramWidth + padding + 20}" y="${headerHeight + 20}" font-family="system-ui" font-size="12" font-weight="600" fill="#e5e7eb">
    Legend
  </text>
  <line x1="${diagramWidth + padding + 20}" y1="${headerHeight + 35}" x2="${diagramWidth + padding + 50}" y2="${headerHeight + 35}" 
        stroke="#3b82f6" stroke-width="2" stroke-dasharray="5,5"/>
  <text x="${diagramWidth + padding + 60}" y="${headerHeight + 40}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Site boundary
  </text>
  <rect x="${diagramWidth + padding + 20}" y="${headerHeight + 50}" width="30" height="20" 
        fill="#22c55e22" stroke="#22c55e" stroke-width="2"/>
  <text x="${diagramWidth + padding + 60}" y="${headerHeight + 65}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Buildable area
  </text>
  <rect x="${diagramWidth + padding + 20}" y="${headerHeight + 80}" width="30" height="20" 
        fill="#f59e0b22" stroke="#f59e0b" stroke-width="1"/>
  <text x="${diagramWidth + padding + 60}" y="${headerHeight + 95}" font-family="system-ui" font-size="10" fill="#9ca3af">
    Setback bands
  </text>
  <text x="${padding}" y="${totalHeight - 20}" font-family="system-ui" font-size="10" fill="#6b7280">
    ${jurisdiction}
  </text>
  <text x="${padding}" y="${totalHeight - 5}" font-family="system-ui" font-size="9" fill="#6b7280" font-style="italic">
    Illustrative only. Confirm against local code.
  </text>
</svg>
`;
}

function wantsDiagram(query: string): boolean {
  const q = query.toLowerCase();
  const triggers = [
    "diagram",
    "draw",
    "sketch",
    "illustrate",
    "show",
    "visualize",
    "plot",
    "envelope",
    "setback",
    "fsi",
    "far",
    "fsr",
    "buildable",
  ];
  return triggers.some((t) => q.includes(t));
}

function pickDiagramKind(query: string): DiagramKind {
  const q = query.toLowerCase();
  if (
    q.includes("setback") ||
    q.includes("envelope") ||
    q.includes("fsi") ||
    q.includes("far") ||
    q.includes("fsr") ||
    q.includes("buildable")
  ) {
    return "buildable_envelope";
  }
  return "annotated_object";
}

type Jurisdiction = "india" | "uk" | "usa";
type Unit = "m" | "ft";
type MetaUnits = "metric" | "imperial";

function detectJurisdiction(query: string): Jurisdiction | null {
  const q = query.toLowerCase();
  const india = ["mumbai", "delhi", "bangalore", "bengaluru"];
  const uk = ["london", "manchester", "birmingham"];
  const usa = ["new york", "nyc", "los angeles", "chicago", "brooklyn"];

  if (india.some((c) => q.includes(c))) return "india";
  if (uk.some((c) => q.includes(c))) return "uk";
  if (usa.some((c) => q.includes(c))) return "usa";
  return null;
}

function parsePlotDimensions(
  query: string
): { length: number; width: number; unit: Unit } | null {
  const q = query.toLowerCase().replace(/\s+/g, " ");
  const mMetric = q.match(
    /(\d+(?:\.\d+)?)\s*m\s*[x×]\s*(\d+(?:\.\d+)?)\s*m/
  );
  if (mMetric) {
    return {
      length: Number(mMetric[1]),
      width: Number(mMetric[2]),
      unit: "m",
    };
  }

  const mFt = q.match(
    /(\d+(?:\.\d+)?)\s*(ft|feet)\s*[x×]\s*(\d+(?:\.\d+)?)\s*(ft|feet)/
  );
  if (mFt) {
    return {
      length: Number(mFt[1]),
      width: Number(mFt[3]),
      unit: "ft",
    };
  }

  const mLooseMetric = q.match(
    /(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*(m|meter|metre|meters|metres)\b/
  );
  if (mLooseMetric) {
    return {
      length: Number(mLooseMetric[1]),
      width: Number(mLooseMetric[2]),
      unit: "m",
    };
  }

  const mLooseFt = q.match(
    /(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*(ft|feet)\b/
  );
  if (mLooseFt) {
    return {
      length: Number(mLooseFt[1]),
      width: Number(mLooseFt[2]),
      unit: "ft",
    };
  }

  return null;
}

function pickUnits(j: Jurisdiction): { metaUnits: MetaUnits; unit: Unit } {
  if (j === "usa") return { metaUnits: "imperial", unit: "ft" };
  return { metaUnits: "metric", unit: "m" };
}

function pickSetbacks(
  query: string,
  j: Jurisdiction,
  dim: { length: number; width: number; unit: Unit } | null
) {
  const q = query.toLowerCase();

  if (j === "india") {
    let front = 3,
      rear = 3,
      side = 2;
    let regulation = "Mumbai DCR (illustrative)";

    if (dim && dim.unit === "m") {
      const area = dim.length * dim.width;
      if (area > 300) {
        front = 5;
        rear = 3;
        side = 3;
      }
      regulation =
        area > 300
          ? "Mumbai DCR (plots > 300 sqm, illustrative)"
          : "Mumbai DCR (plots < 300 sqm, illustrative)";
    }

    const isCorner = q.includes("corner");
    return {
      front,
      rear,
      left: isCorner ? 0 : side,
      right: side,
      unit: "m" as const,
      regulation: q.includes("dcr 33") ? "DCR 33(7)" : regulation,
    };
  }

  if (j === "uk") {
    return {
      front: 2,
      rear: 1.5,
      left: 1,
      right: 1,
      unit: "m" as const,
      regulation: "Town Planning Guidelines (illustrative)",
    };
  }

  const isR4 = q.includes("r4");
  if (isR4) {
    return {
      front: 15,
      rear: 15,
      left: 8,
      right: 8,
      unit: "ft" as const,
      regulation: "NYC Zoning R4 (illustrative)",
    };
  }
  return {
    front: 10,
    rear: 10,
    left: 5,
    right: 5,
    unit: "ft" as const,
    regulation: "NYC Zoning R3 (illustrative)",
  };
}

function rectToPolygon(x: number, y: number, w: number, h: number) {
  return [
    { x, y },
    { x: x + w, y },
    { x: x + w, y: y + h },
    { x, y: y + h },
  ];
}

function insetRectPolygon(
  poly: { x: number; y: number }[],
  inset: { top: number; right: number; bottom: number; left: number }
) {
  const tl = poly[0];
  const tr = poly[1];
  const br = poly[2];
  const bl = poly[3];

  const minX = Math.min(tl.x, bl.x);
  const maxX = Math.max(tr.x, br.x);
  const minY = Math.min(tl.y, tr.y);
  const maxY = Math.max(bl.y, br.y);

  const nx1 = minX + inset.left;
  const nx2 = maxX - inset.right;
  const ny1 = minY + inset.top;
  const ny2 = maxY - inset.bottom;

  if (nx2 <= nx1 || ny2 <= ny1) return null;

  return rectToPolygon(nx1, ny1, nx2 - nx1, ny2 - ny1);
}

function buildBuildableEnvelopeDiagram(query: string): DiagramPayload {
  const j = detectJurisdiction(query) ?? "india";
  const dim = parsePlotDimensions(query);
  const { metaUnits, unit } = pickUnits(j);
  const setbacks = pickSetbacks(query, j, dim);

  const titleBase = "Buildable Envelope";
  const title = dim
    ? `${titleBase} for ${dim.length}${dim.unit} × ${dim.width}${dim.unit} Plot (${j.toUpperCase()})`
    : `${titleBase} (${j.toUpperCase()})`;

  const canvas = { width: 900, height: 520, padding: 24 };
  const marginLeft = 140;
  const marginTop = 120;
  const siteW = 620;
  const siteH = 300;

  const sitePolygon = rectToPolygon(marginLeft, marginTop, siteW, siteH);

  let insetPx = { top: 40, right: 35, bottom: 30, left: 35 };
  if (dim) {
    const pxPerX = siteW / dim.length;
    const pxPerY = siteH / dim.width;
    insetPx = {
      top: setbacks.front * pxPerY,
      bottom: setbacks.rear * pxPerY,
      left: setbacks.left * pxPerX,
      right: setbacks.right * pxPerX,
    };
  }

  const buildablePolygon = insetRectPolygon(sitePolygon, insetPx);

  let buildableArea: number | undefined;
  let coverage: number | undefined;
  if (dim) {
    const bLen = Math.max(0, dim.length - setbacks.left - setbacks.right);
    const bWid = Math.max(0, dim.width - setbacks.front - setbacks.rear);
    const siteArea = dim.length * dim.width;
    const bArea = bLen * bWid;
    buildableArea = Math.round(bArea * 100) / 100;
    coverage =
      siteArea > 0 ? Math.round((bArea / siteArea) * 10000) / 100 : undefined;
  }

  const spec = {
    meta: {
      title,
      domain: "urban_planning",
      diagramType: "buildable_envelope",
      units: metaUnits,
      notes: "Illustrative only. Confirm against local code.",
      jurisdiction: j,
      regulation: setbacks.regulation,
    },
    canvas,
    site: {
      polygon: sitePolygon,
      ...(dim
        ? { dimensions: { length: dim.length, width: dim.width, unit } }
        : {}),
    },
    setbacks: {
      front: setbacks.front,
      rear: setbacks.rear,
      left: setbacks.left,
      right: setbacks.right,
      unit: setbacks.unit,
    },
    computed: {
      ...(buildablePolygon ? { buildablePolygon } : {}),
      ...(buildableArea != null ? { buildableArea } : {}),
      ...(coverage != null ? { coverage } : {}),
    },
    legend: [
      { label: "Site boundary", style: "site" },
      { label: "Buildable area", style: "buildable" },
      { label: "Setback bands", style: "setback_band" },
    ],
  };

  return { kind: "buildable_envelope", title, spec };
}

async function generateAnnotatedObjectDiagram(
  query: string
): Promise<DiagramPayload | null> {
  const system = `Output ONLY valid JSON. No markdown. No commentary.
diagramType must be "annotated_object".`;

  const user = `Return JSON with this shape:

{
  "meta": { "title": string, "domain": "construction"|"real_estate"|"urban_planning", "diagramType":"annotated_object", "units":"metric"|"imperial", "standard"?: string },
  "canvas": { "width": 900, "height": 500, "padding": 24 },
  "object": { "kind": string, "bbox": { "x": 120, "y": 80, "w": 220, "h": 320 }, "labels": string[] },
  "callouts": [ { "anchor": { "x": number, "y": number }, "leader": { "x": number, "y": number }, "text": string } ]
}

Query: ${query}`;

  const completion = await groq.chat.completions.create({
    model: GROQ_CHAT_MODEL,
    messages: [
      { role: "system", content: system },
      { role: "user", content: user },
    ],
    temperature: 0.2,
    max_tokens: 1200,
    top_p: 1,
  });

  const raw = completion.choices[0]?.message?.content?.trim();
  if (!raw) return null;

  try {
    const spec = JSON.parse(raw);
    const title = spec?.meta?.title;
    if (!title || typeof title !== "string") return null;
    return { kind: "annotated_object", title, spec };
  } catch {
    return null;
  }
}

// =============================================================================
// SEARCH + ANSWER GENERATION
// =============================================================================

async function searchRAG(
  query: string,
  region: "india" | "uk" | "usa" | null,
  topK = 25,
  threshold = 0.3
): Promise<EnhancedChunk[]> {
  const optimizedQuery = optimizeQuery(query);
  const embedding = await generateEmbedding(optimizedQuery);

  const { data, error } = await supabase.rpc("match_rag_chunks", {
    query_embedding: embedding,
    match_threshold: 1 - threshold,
    match_count: topK,
    filter_region: region || null,
  });

  if (error) {
    console.error("searchRAG RPC error:", error);
    throw new Error(`RAG search failed: ${error.message}`);
  }

  const rows = Array.isArray(data) ? data : [];

  return rows.map((row: any) => ({
    id: Number(row.id),
    region: String(row.region || ""),
    jurisdiction: String(row.jurisdiction || row.region || ""),
    doc_title: String(row.doc_title || "Untitled document"),
    doc_path: String(row.doc_path || ""),
    doc_kind: String(row.doc_kind || "regulation"),
    doc_authority: row.doc_authority ?? null,
    doc_publication_date: row.doc_publication_date ?? null,
    doc_version: row.doc_version ?? null,
    page_from:
      row.page_from === null || row.page_from === undefined
        ? null
        : Number(row.page_from),
    page_to:
      row.page_to === null || row.page_to === undefined
        ? null
        : Number(row.page_to),
    line_from:
      row.line_from === null || row.line_from === undefined
        ? null
        : Number(row.line_from),
    line_to:
      row.line_to === null || row.line_to === undefined
        ? null
        : Number(row.line_to),
    citation_type: row.citation_type ?? null,
    citation_value: row.citation_value ?? null,
    citation_full: row.citation_full ?? null,
    clause_label: row.clause_label ?? null,
    all_clauses: row.all_clauses ?? null,
    section_heading: row.section_heading ?? null,
    section_hierarchy: row.section_hierarchy ?? null,
    cross_refs: row.cross_refs ?? null,
    table_refs: Array.isArray(row.table_refs) ? row.table_refs : null,
    schedule_refs: Array.isArray(row.schedule_refs) ? row.schedule_refs : null,
    annexure_refs: Array.isArray(row.annexure_refs) ? row.annexure_refs : null,
    has_table: Boolean(row.has_table),
    has_formula: Boolean(row.has_formula),
    has_diagram:
      row.has_diagram === undefined ? undefined : Boolean(row.has_diagram),
    keywords: Array.isArray(row.keywords) ? row.keywords : null,
    topic: row.topic ?? null,
    subtopic: row.subtopic ?? null,
    content: String(row.content || ""),
    distance:
      typeof row.distance === "number"
        ? row.distance
        : Number(row.distance ?? 1),
    indexed_at: String(row.indexed_at || new Date().toISOString()),
    updated_at: row.updated_at ?? null,
  }));
}

async function generateAnswer(
  query: string,
  chunks: EnhancedChunk[],
  webCitations: TransformedCitation[],
  feasibilitySection = "",
  drawingValidation?: any
): Promise<{
  answerMarkdown: string;
  missingCoverage: Array<{
    questionPart: string;
    resolvedFrom: "document" | "web" | "unresolved";
  }>;
}> {
  const chosenChunks = chooseChunksForAnswer(query, chunks);
  const strictDocumentContext = buildStrictDocumentContext(chosenChunks);
  const webContext = buildWebContext(webCitations);

  const drawingSection = drawingValidation
    ? `

DRAWING VALIDATION RESULTS (structured data – do not change numbers, just explain logically):
${JSON.stringify(drawingValidation, null, 2)}`
    : "";

  const systemPrompt = `${systemMessage}

You must follow these rules strictly:

1. Answer primarily from DOCUMENT context.
2. Use inline citations like [D1], [D2] for document-backed claims.
3. Use [W1], [W2] only for claims supported by web fallback.
4. Never invent page numbers, clause numbers, or regulations.
5. If the answer is not supported, say so clearly.
6. Keep the answer structured in markdown.
7. Do not output JSON unless explicitly asked.
8. Do not mention sources you did not use.
9. If document evidence is strong, do not rely on web.
10. If feasibility or drawing data is provided, explain it without changing numeric values.`;

  const userPrompt = `
User query:
${query}

DOCUMENT CONTEXT:
${strictDocumentContext || "No document context available."}

WEB CONTEXT:
${webContext || "No web context available."}
${feasibilitySection || ""}${drawingSection}

Return JSON only in this exact shape:
{
  "answerMarkdown": "markdown answer with inline citations like [D1], [D2], [W1]",
  "missingCoverage": [
    {
      "questionPart": "string",
      "resolvedFrom": "document" | "web" | "unresolved"
    }
  ]
}
`.trim();

  try {
    const completion = await groq.chat.completions.create({
      model: GROQ_CHAT_MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 2200,
      top_p: 1,
    });

    const raw = completion.choices?.[0]?.message?.content?.trim() || "";
    const jsonText = extractFirstJsonObject(raw);

    if (!jsonText) {
      return {
        answerMarkdown: buildPartialCoverageAnswer(),
        missingCoverage: [
          {
            questionPart: query,
            resolvedFrom: "unresolved",
          },
        ],
      };
    }

    const parsed = JSON.parse(jsonText);

    let answerMarkdown =
      typeof parsed?.answerMarkdown === "string"
        ? parsed.answerMarkdown.trim()
        : "";

    let missingCoverage: Array<{
      questionPart: string;
      resolvedFrom: "document" | "web" | "unresolved";
    }> = Array.isArray(parsed?.missingCoverage)
      ? parsed.missingCoverage.map((m: any) => ({
          questionPart: String(m?.questionPart || query),
          resolvedFrom:
            m?.resolvedFrom === "document" ||
            m?.resolvedFrom === "web" ||
            m?.resolvedFrom === "unresolved"
              ? m.resolvedFrom
              : "unresolved",
        }))
      : [];

    if (!answerMarkdown) {
      answerMarkdown = buildPartialCoverageAnswer();
    }

    if (shouldRejectWeakExtraction(query, answerMarkdown)) {
      const extractionPrompt = buildExtractionPrompt(
        query,
        strictDocumentContext
      );

      const retryCompletion = await groq.chat.completions.create({
        model: GROQ_CHAT_MODEL,
        messages: [
          {
            role: "system",
            content:
              "You are a precise regulatory extraction engine. Output valid JSON only.",
          },
          {
            role: "user",
            content: extractionPrompt,
          },
        ],
        temperature: 0.1,
        max_tokens: 2200,
        top_p: 1,
      });

      const retryRaw =
        retryCompletion.choices?.[0]?.message?.content?.trim() || "";
      const retryJson = extractFirstJsonObject(retryRaw);

      if (retryJson) {
        const retryParsed = JSON.parse(retryJson);

        const retryAnswer =
          typeof retryParsed?.answerMarkdown === "string"
            ? retryParsed.answerMarkdown.trim()
            : "";

        const retryMissingCoverage: Array<{
          questionPart: string;
          resolvedFrom: "document" | "web" | "unresolved";
        }> = Array.isArray(retryParsed?.missingCoverage)
          ? retryParsed.missingCoverage.map((m: any) => ({
              questionPart: String(m?.questionPart || query),
              resolvedFrom:
                m?.resolvedFrom === "document" ||
                m?.resolvedFrom === "web" ||
                m?.resolvedFrom === "unresolved"
                  ? m.resolvedFrom
                  : "unresolved",
            }))
          : [];

        if (retryAnswer) {
          answerMarkdown = retryAnswer;
          missingCoverage = retryMissingCoverage;
        }
      }
    }

    if (!missingCoverage.length) {
      missingCoverage = [
        {
          questionPart: query,
          resolvedFrom: chunks.length
            ? "document"
            : webCitations.length
            ? "web"
            : "unresolved",
        },
      ];
    }

    return {
      answerMarkdown,
      missingCoverage,
    };
  } catch (error) {
    console.error("generateAnswer failed:", error);

    return {
      answerMarkdown: buildPartialCoverageAnswer(),
      missingCoverage: [
        {
          questionPart: query,
          resolvedFrom: "unresolved",
        },
      ],
    };
  }
}

// =============================================================================
// ROUTE HANDLERS
// =============================================================================

export async function POST(req: Request) {
  const start = Date.now();

  try {
    let body: RagRequest;

    const contentType = req.headers.get("content-type") || "";

    if (contentType.includes("application/json")) {
      body = (await req.json()) as RagRequest;
    } else if (contentType.includes("multipart/form-data")) {
      const form = await req.formData();
      body = {
        query: String(form.get("query") || ""),
        mode:
          (String(form.get("mode") || "auto") as
            | "auto"
            | "feasibility"
            | "permitting"
            | "risk") || "auto",
        drawingFile: (form.get("drawingFile") as File) || undefined,
      };
    } else {
      body = (await req.json()) as RagRequest;
    }

    if (!body?.query || typeof body.query !== "string") {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid request: query is required",
        } satisfies RagResponse,
        { status: 400 }
      );
    }

    const query = body.query;

    const knownPatterns = await loadQuestionPatterns();
    const diagramIntent = detectDiagramIntent(query, knownPatterns);
    console.log("📊 Diagram Intent Analysis:", {
      shouldGenerate: diagramIntent.shouldGenerate,
      type: diagramIntent.type,
      confidence: Math.round(diagramIntent.confidence * 100) + "%",
      patterns: diagramIntent.matchedPatterns,
    });

    const region = body.region ?? null;
    const topK = Number.isFinite(body.topK as any)
      ? Math.max(1, Math.min(50, body.topK!))
      : 25;
    const threshold = Number.isFinite(body.threshold as any)
      ? Math.max(0, Math.min(1, body.threshold!))
      : 0.3;
    const includeMetadata = body.includeMetadata !== false;

    const validRegions = ["india", "uk", "usa"];
    if (region && !validRegions.includes(region)) {
      return NextResponse.json(
        {
          success: false,
          error: `Invalid region. Must be one of: ${validRegions.join(", ")}`,
        } satisfies RagResponse,
        { status: 400 }
      );
    }

    const mode = body.mode ?? "auto";

    let feasibilitySection = "";
    let feasibilityReport: any | undefined = undefined;

    if (mode === "feasibility" && body.feasibilityInputs) {
      try {
        const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "";
        const feasRes = await fetch(`${baseUrl}/api/feasibility`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body.feasibilityInputs),
        });
        const feasJson = await feasRes.json();
        if (feasRes.ok && feasJson?.success) {
          feasibilityReport = feasJson.feasibilityReport;
          feasibilitySection = `\n\nFEASIBILITY SNAPSHOT (structured data – do not change numbers, just explain logically):\n\n${JSON.stringify(
            feasibilityReport,
            null,
            2
          )}`;
        } else {
          console.warn("Feasibility API error:", feasJson?.error);
        }
      } catch (err) {
        console.error("Error calling /api/feasibility:", err);
      }
    }

    let drawingValidation: any | undefined = undefined;

    if (mode === "feasibility" && body.drawingFile) {
      try {
        const location = body.feasibilityInputs?.city
          ?.toLowerCase()
          .includes("london")
          ? "london"
          : "nyc";

        const drawingFormData = new FormData();

        if (
          body.drawingFile instanceof File ||
          body.drawingFile instanceof Blob
        ) {
          drawingFormData.append("drawing", body.drawingFile);
        } else if (typeof body.drawingFile === "string") {
          console.warn("Drawing file is a string, conversion needed");
        }
        drawingFormData.append("location", location);

        const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "";
        const drawingRes = await fetch(`${baseUrl}/api/analyze-drawing`, {
          method: "POST",
          body: drawingFormData,
        });

        const drawingAnalysis = await drawingRes.json();

        if (drawingRes.ok && drawingAnalysis?.success) {
          const { validateLondon } = await import(
            "@/lib/validators/london-uk-validator"
          );
          const { validateNYC } = await import(
            "@/lib/validators/nyc-usa-validator"
          );

          drawingValidation =
            location === "london"
              ? validateLondon(drawingAnalysis.analysis)
              : validateNYC(
                  drawingAnalysis.analysis,
                  body.feasibilityInputs?.zoneCode || "R4"
                );

          console.log(
            `✅ Drawing validated: ${drawingValidation.violations.length} violations, ${drawingValidation.warnings.length} warnings`
          );
        } else {
          console.warn("Drawing analysis failed:", drawingAnalysis?.error);
        }
      } catch (err) {
        console.error("Error analyzing drawing:", err);
      }
    }

    console.log("⏱️ STEP 1: starting searchRAG");
    let chunks = await searchRAG(query, region, topK, threshold);
    console.log("⏱️ STEP 1 DONE: searchRAG returned", chunks.length, "chunks");

    console.log("⏱️ STEP 2: reranking");
    chunks = reRankByCitations(chunks, query);
    chunks = reRankByKeywords(chunks, query);
    chunks = rankRetrievedChunks(query, chunks);
    console.log("⏱️ STEP 2 DONE: reranking complete");

    console.log("⏱️ STEP 3: document-region filtering");
    const requestedDocRegion = detectRequestedDocumentRegion(query);
    if (requestedDocRegion) {
      const filtered = chunks.filter(
        (c) => lower(c.region) === requestedDocRegion
      );
      if (filtered.length) {
        chunks = filtered;
      }
    }
    console.log("⏱️ STEP 3 DONE: filtered chunks =", chunks.length);
    console.log(
      "🔎 TOP RANKED CHUNKS:",
      chunks.slice(0, 12).map((c, i) => ({
        rank: i + 1,
        page: c.page_from,
        heading: c.section_heading,
        hierarchy: c.section_hierarchy,
        clause: c.clause_label,
        citationType: c.citation_type,
        citationValue: c.citation_value,
        tableRefs: c.table_refs,
        topic: c.topic,
        preview: c.content.slice(0, 350),
      }))
    );

    if (
      isThresholdQuery(query) &&
      lower(query).includes("firefighting shaft")
    ) {
      console.log("⏱️ THRESHOLD OVERRIDE: firefighting shaft extraction");

      const relevantThresholdChunks = chunks
        .map((c) => ({
          chunk: c,
          priority: getFirefightingShaftClausePriority(c),
        }))
        .filter(({ priority, chunk }) => {
          const text = normalizedForMatching(chunk.content || "");
          const heading = normalizedForMatching(chunk.section_heading || "");
          const section = normalizedForMatching(chunk.section_hierarchy || "");

          const hasTopic =
            text.includes("firefighting shaft") ||
            heading.includes("firefighting shaft") ||
            section.includes("firefighting shaft") ||
            lower(chunk.clause_label).startsWith("17.") ||
            lower(chunk.citation_value).startsWith("17.");

          return hasTopic && priority > 0;
        })
        .sort(
          (a, b) => b.priority - a.priority || a.chunk.distance - b.chunk.distance
        )
        .map(({ chunk }) => chunk);

      console.log(
        "⏱️ THRESHOLD OVERRIDE DEBUG:",
        relevantThresholdChunks.slice(0, 8).map((c) => ({
          page: c.page_from,
          clause: c.clause_label,
          citation: c.citation_value,
          heading: c.section_heading,
          priority: getFirefightingShaftClausePriority(c),
          preview: sanitizeEvidenceText(c.content).slice(0, 220),
        }))
      );

      const primaryChunks = relevantThresholdChunks.filter((c) => {
        const text = normalizedForMatching(c.content || "");
        const clause = lower(c.clause_label);
        const citation = lower(c.citation_value);

        return (
          clause === "17.2" ||
          citation === "17.2" ||
          text.includes(
            "storey more than 18 m above the fire and rescue service vehicle access level"
          )
        );
      });

      const relatedChunks = relevantThresholdChunks.filter((c) => {
        const clause = lower(c.clause_label);
        const citation = lower(c.citation_value);
        return (
          ["17.3", "17.4", "17.5", "17.6"].includes(clause) ||
          ["17.3", "17.4", "17.5", "17.6"].includes(citation)
        );
      });

      const finalThresholdChunks = [...primaryChunks, ...relatedChunks].slice(
        0,
        4
      );

      const thresholdCitations = dedupeCitations(
        transformChunksForFrontend(finalThresholdChunks)
      ).slice(0, 4);

      const primaryCitation =
        thresholdCitations.find((c) => c.clauseNumber === "17.2") ||
        thresholdCitations[0];
      const relatedCitations = thresholdCitations.filter(
        (c) => c !== primaryCitation
      );

      if (primaryCitation) {
        let answer = `### Direct Answer
A firefighting shaft is required where a building has **a storey more than 18 m above the fire and rescue service vehicle access level**. [${primaryCitation.id}]`;

        if (relatedCitations.length > 0) {
          const relatedRefs = relatedCitations.map((c) => `[${c.id}]`).join(" ");
          answer += `

### Related Provisions
Additional firefighting shaft provisions apply to certain basement conditions and, in some cases, to buildings requiring multiple firefighting shafts. ${relatedRefs}`;
        }

        answer = sanitizeEvidenceText(answer);
        answer += buildReferencesBlock(thresholdCitations, []);

        return NextResponse.json(
          {
            success: true,
            answer,
            data: {
              citations: thresholdCitations,
              query,
              region,
              resultsCount: finalThresholdChunks.length,
              metadata: includeMetadata
                ? calculateMetadata(finalThresholdChunks)
                : undefined,
              references: {
                documents: thresholdCitations,
                web: [],
              },
              missingCoverage: [
                {
                  questionPart: query,
                  resolvedFrom: "document",
                },
              ],
              feasibilityReport,
              drawingValidation,
            },
            metadata: {
              processing_time: Date.now() - start,
              confidence: 74,
              webFallbackUsed: false,
            },
          } satisfies RagResponse,
          { status: 200 }
        );
      }

      console.log(
        "⏱️ THRESHOLD OVERRIDE: no usable citations, continuing normal flow"
      );
    }

    if (isTableQuery(query)) {
      console.log("⏱️ TABLE OVERRIDE: attempting direct numeric extraction");

      const relevantTableChunks = chunks
        .filter((c) => {
          const t = lower(c.content);
          return (
            t.includes("table 2.1") ||
            t.includes("travel distance") ||
            /\b\d+\s?m\b/.test(t)
          );
        })
        .slice(0, 8);

      const combinedTableText = relevantTableChunks.map((c) => c.content).join("\n");
      const extractedDistances = combinedTableText.match(/\b\d+\s?m\b/gi) || [];

      const cleanedDistances = extractedDistances.filter((d) => {
        const val = parseInt(d, 10);
        return val >= 10 && val <= 120;
      });

      const uniqueDistances = Array.from(
        new Set(cleanedDistances.map((x) => x.trim()))
      );

      if (uniqueDistances.length > 0) {
        const tableCitations = dedupeCitations(
          transformChunksForFrontend(relevantTableChunks)
        ).slice(0, 5);

        let answer = `### Direct Answer
The following distance values were extracted from the retrieved Table 2.1 context: ${uniqueDistances.join(", ")}.

### Notes
These values were extracted directly from fragmented table-related chunks. They should be verified against the original table layout in Approved Document B.`;

        answer = sanitizeEvidenceText(answer);

        if (tableCitations.length > 0) {
          answer += buildReferencesBlock(tableCitations, []);
        }

        return NextResponse.json(
          {
            success: true,
            answer,
            data: {
              citations: tableCitations,
              query,
              region,
              resultsCount: relevantTableChunks.length,
              metadata: includeMetadata
                ? calculateMetadata(relevantTableChunks)
                : undefined,
              references: {
                documents: tableCitations,
                web: [],
              },
              missingCoverage: [],
              feasibilityReport,
              drawingValidation,
            },
            metadata: {
              processing_time: Date.now() - start,
              confidence: 60,
              webFallbackUsed: false,
            },
          } satisfies RagResponse,
          { status: 200 }
        );
      }
    }

    console.log("⏱️ STEP 4: building citations");
    let documentCitations = dedupeCitations(transformChunksForFrontend(chunks));
    console.log(
      "⏱️ STEP 4 DONE: document citations =",
      documentCitations.length
    );

    console.log("⏱️ STEP 5: checking web fallback");
    const useWebFallback = shouldUseWebFallback(query, chunks);
    console.log("⏱️ STEP 5 INFO: useWebFallback =", useWebFallback);

    const webCitations = useWebFallback ? await fetchWebFallback(query) : [];

    console.log("⏱️ STEP 5 DONE: web citations =", webCitations.length);

    console.log("⏱️ STEP 6: preparing answer gating");
    const topSimilarity = getTopSimilarityScore(chunks);
    const jurisdictionMismatch = hasJurisdictionMismatch(query, chunks);
    const explicitlyOutside = isOutsideDatasetQuery(query);

    let answerResult: {
      answerMarkdown: string;
      missingCoverage: Array<{
        questionPart: string;
        resolvedFrom: "document" | "web" | "unresolved";
      }>;
    };

    if (!chunks.length || explicitlyOutside || jurisdictionMismatch) {
      console.log("⏱️ STEP 6 RESULT: outside-dataset / mismatch fallback");
      documentCitations = [];
      answerResult = {
        answerMarkdown: buildOutsideDatasetAnswer(),
        missingCoverage: [
          {
            questionPart: query,
            resolvedFrom: "unresolved",
          },
        ],
      };
    } else if (
      !isComparisonQuery(query) &&
      !isTableQuery(query) &&
      !isThresholdQuery(query) &&
      topSimilarity < 0.72
    ) {
      console.log("⏱️ STEP 6 RESULT: partial-coverage fallback");
      answerResult = {
        answerMarkdown: buildPartialCoverageAnswer(),
        missingCoverage: [
          {
            questionPart: query,
            resolvedFrom: "document",
          },
        ],
      };
    } else {
      console.log("⏱️ STEP 7: calling generateAnswer");
      answerResult = await generateAnswer(
        query,
        chunks,
        webCitations,
        feasibilitySection,
        drawingValidation
      );
      console.log("⏱️ STEP 7 DONE: generateAnswer returned");
    }

    const answerFailedReliably =
      answerResult.answerMarkdown?.includes(
        "I cannot answer reliably from the indexed documents."
      ) || false;

    if (answerFailedReliably) {
      documentCitations = documentCitations.slice(0, 3);
    }

    const allCitations = [...documentCitations, ...webCitations];

    const meta = includeMetadata ? calculateMetadata(chunks) : undefined;
    const processing_time = Date.now() - start;
    const avgDistance = meta?.avgDistance ?? 0;

    let confidence = Math.round(
      calculateConfidence(avgDistance, chunks.length) * 100
    );

    const dirtyChunkCount = countDirtyChunks(chunks);
    const dirtyPenalty = Math.min(18, dirtyChunkCount * 4);
    confidence = Math.max(0, confidence - dirtyPenalty);

    if (!chunks.length || explicitlyOutside || jurisdictionMismatch) {
      confidence = 0;
    } else if (
      !isComparisonQuery(query) &&
      !isTableQuery(query) &&
      !isThresholdQuery(query) &&
      topSimilarity < 0.72
    ) {
      confidence = Math.min(confidence, 25);
    } else if (answerFailedReliably) {
      confidence = Math.min(confidence, 25);
    }

    let diagram: DiagramPayload | undefined;
    let svgContent: string | undefined;

    const shouldDiagram =
      diagramIntent.shouldGenerate ||
      body.wantDiagram === true ||
      wantsDiagram(query);

    let cleanedAnswer = forceAtLeastOneInlineCitation(
      answerResult.answerMarkdown,
      documentCitations,
      webCitations
    );

    cleanedAnswer = sanitizeEvidenceText(cleanedAnswer);

    if (shouldDiagram) {
      const kind = pickDiagramKind(query);
      if (kind === "buildable_envelope") {
        diagram = buildBuildableEnvelopeDiagram(query);
      } else {
        const generated = await generateAnnotatedObjectDiagram(query);
        if (generated) diagram = generated;
      }

      if (shouldGenerateDiagram(cleanedAnswer)) {
        const extractedDiagram = extractDiagramSpec(cleanedAnswer);
        if (extractedDiagram) {
          diagram = extractedDiagram;
        }
        cleanedAnswer = removeJsonBlock(cleanedAnswer);
      }

      if (diagram && diagram.kind === "buildable_envelope") {
        svgContent = generateDiagramSVG(diagram);
      }
    }

    const finalAnswer = cleanedAnswer
      .replace(/\n#{1,6}\s+References[\s\S]*$/i, "")
      .trim();

    const response: RagResponse = {
      success: true,
      answer: finalAnswer,
      diagram,
      svgContent,
      data: {
        citations: allCitations,
        query,
        region,
        resultsCount: chunks.length,
        metadata: meta,
        references: {
          documents: documentCitations,
          web: webCitations,
        },
        missingCoverage: answerResult.missingCoverage,
        feasibilityReport,
        drawingValidation,
      },
      metadata: {
        processing_time,
        confidence,
        webFallbackUsed: webCitations.length > 0,
      },
    };

    return NextResponse.json(response, { status: 200 });
  } catch (e: any) {
    console.error("❌ RAG API Error:", e);
    return NextResponse.json(
      {
        success: false,
        error: e?.message || "Internal server error",
      } satisfies RagResponse,
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    status: "healthy",
    timestamp: new Date().toISOString(),
    message:
      "RAG chat endpoint with Google embeddings + Groq LLM + diagram generation + SVG rendering + drawing analysis (UK/US)",
    endpoints: { POST: "/api/rag-chat" },
  });
}